import {test} from 'node:test';import assert from 'node:assert/strict';
import {Transport,ProviderError} from '../dist/providers/transport.js';import {V1Adapter} from '../dist/providers/v1.js';import {V4Adapter} from '../dist/providers/v4.js';
const request={sha256:'a'.repeat(64),size:10,filename:'source.pdf',tier:'standard',formats:['markdown','json']};
test('modern V1 uses uploads and parse/jobs; completed uploads skip transfer and unknown outputs survive',async()=>{
 const calls=[];const t={json:async(path,method,body)=>{calls.push({path,method,body});if(path==='uploads')return{id:'u',status:'completed',file:{id:'f'}};if(path==='parse/jobs')return{job_id:'j',status:'queued'};if(path==='parse/jobs/j')return{job_id:'j',status:'partial',files:[{status:'completed',output_files:{markdown:{file_id:'md'},novel:{file_id:'opaque'}}}]};},bytes:async()=>{throw Error('no transfer expected');}};
 const a=new V1Adapter('https://mineru.example/api/v1',t),upload=await a.prepare(request);assert.equal(upload.fileId,'f');await a.transfer(upload,Buffer.from('x'));assert.equal(await a.submit(request,upload.fileId),'j');const status=await a.status('j');assert.equal(status.state,'partial');assert.deepEqual(status.outputs.map(o=>o.format),['markdown','novel']);assert.ok(calls.every(c=>!c.path.includes('agent/parse')));await assert.rejects(a.prepare({...request,pages:'1-2'}),{code:'unsupported_capability'});
});
test('transport attaches auth only same-origin and strips it on redirect including other port',async()=>{
 const calls=[];const fetcher=async(url,init)=>{calls.push({url:String(url),auth:new Headers(init.headers).get('authorization')});return calls.length===1?new Response(null,{status:302,headers:{location:'https://service.example:444/file?signature=PRIVATE'}}):new Response('bytes');};
 const t=new Transport('https://service.example/api/v1','SECRET',fetcher);assert.equal((await t.apiBytes('files/f/content')).toString(),'bytes');assert.equal(calls[0].auth,'Bearer SECRET');assert.equal(calls[1].auth,null);
});
test('provider failures never return response messages, credential headers or signed URLs',async()=>{
 const t=new Transport('https://service.example/api/v1','SECRET',async()=>{throw Error('Bearer SECRET https://storage/?signature=PRIVATE');});await assert.rejects(t.json('uploads','POST',{}),e=>e.code==='transport_failed'&&!e.message.includes('SECRET')&&e.uncertain);
});
test('V4 upload allocation correlates exact hash and unknown provider state remains unknown',async()=>{
 const calls=[];const t={json:async(path,method,body)=>{calls.push({path,method,body});return{code:0,data:path==='file-urls/batch'?{batch_id:'b',file_urls:['https://storage.test/signed']}:{batch_id:'b',extract_result:[{state:'future'}]}}}};const a=new V4Adapter('https://mineru.example/api/v4',t);await a.prepare({...request,tier:undefined,model:'vlm'});assert.equal(calls[0].body.files[0].data_id,request.sha256);assert.equal((await a.status('b')).state,'unknown');
});
test('same-origin redirects strip credentials and transfer URL uses only returned headers',async()=>{
 const calls=[];const fetcher=async(url,init)=>{calls.push({url:String(url),headers:new Headers(init.headers)});return calls.length===1?new Response(null,{status:302,headers:{location:'https://service.example/redirect'}}):new Response('ok');};const t=new Transport('https://service.example/api/v1','SECRET',fetcher);await t.apiBytes('files/a/content');assert.equal(calls[0].headers.get('authorization'),'Bearer SECRET');assert.equal(calls[1].headers.get('authorization'),null);
 const transfer=[];await new Transport('https://service.example/api/v1','SECRET',async(url,init)=>{transfer.push(new Headers(init.headers));return new Response(null,{status:204});}).bytes('https://service.example/signed',{method:'PUT',headers:{'x-upload':'required'}});assert.equal(transfer[0].get('authorization'),null);assert.equal(transfer[0].get('x-upload'),'required');
});
test('nonpublic or non-HTTPS transport targets and redirects fail before fetch',async()=>{let count=0;const t=new Transport('https://service.example/api/v1','SECRET',async()=>{count++;return new Response('bad');});for(const target of ['http://service.example/x','https://127.0.0.1/x','https://[::1]/x','https://169.254.169.254/x','https://10.0.0.1/x','https://localhost/x'])await assert.rejects(t.bytes(target),{code:'invalid_transport_url'});assert.equal(count,0);});
test('V1 single-source adapter rejects provider multi-file response',async()=>{const a=new V1Adapter('https://service.example/api/v1',{json:async()=>({job_id:'j',status:'completed',files:[{status:'completed',output_files:{}},{status:'completed',output_files:{}}]})});await assert.rejects(a.status('j'),{code:'invalid_provider_response'});});
test('capability refresh uses modern health and separate tiers list endpoint',async()=>{const paths=[];const a=new V1Adapter('https://service.example/api/v1',{json:async path=>{paths.push(path);return path==='health'?{features:{sources:['file_id','url'],output_formats:['markdown','json','zip']}}:{object:'list',data:[{id:'standard',description:'current tier',current_model:'mutable-model'}]};}});const local=await a.capabilities();assert.equal(local.tiers,null);assert.deepEqual(paths,[]);const refreshed=await a.capabilities(true);assert.deepEqual(paths,['health','tiers']);assert.deepEqual(refreshed.tiers,['standard']);});
test('pinned DNS lookup supports modern Node all-address and legacy scalar callbacks',async()=>{const {pinnedLookup}=await import('../dist/providers/transport.js');const checked={address:'93.184.216.34',family:4};const lookup=pinnedLookup(checked);lookup('example.test',{all:true},(error,addresses)=>{assert.equal(error,null);assert.deepEqual(addresses,[checked]);});lookup('example.test',{},(error,address,family)=>{assert.equal(error,null);assert.equal(address,checked.address);assert.equal(family,4);});});
test('all transfer URL spellings stay unauthenticated unless provider supplies a header',async()=>{const calls=[];const t=new Transport('https://service.example/api/v1','SECRET',async(url,init)=>{calls.push(new Headers(init.headers));return new Response('ok');});for(const url of ['HTTPS://service.example/signed','//service.example/signed','signed'])await t.bytes(url,{method:'PUT'});assert.equal(calls.length,3);for(const h of calls)assert.equal(h.get('authorization'),null);});
