import {Transport,ProviderError,id,list} from './transport.js';
import type {Adapter,Capabilities,Request,Upload,Snapshot,Output} from './types.js';
/** Modern uploads/parse/jobs API; deliberately unrelated to agent/parse. */
export class V1Adapter implements Adapter {
 readonly api='v1' as const;private cached:Capabilities;
 constructor(readonly endpoint:string,private transport=new Transport(endpoint)){if(!/\/(?:api\/)?v1\/?$/.test(new URL(endpoint).pathname))throw new ProviderError('invalid_v1_endpoint');this.cached={api:'v1',endpoint,observed_at:null,validation:'fixture-only',sources:null,formats:null,tiers:null,ranges:false,remote_cancel:false,lost_id_lookup:false};}
 async capabilities(refresh=false){if(refresh){const h=await this.transport.json('health');const tiers=await this.transport.json('tiers');if(tiers.object!=='list'||!Array.isArray(tiers.data))throw new ProviderError('invalid_capabilities');this.cached={...this.cached,observed_at:new Date().toISOString(),sources:list(h.features?.sources),formats:list(h.features?.output_formats),tiers:tiers.data.map((x:any)=>id(x.id))};}return this.cached;}
 private upload(r:any):Upload {const uploadId=id(r.id);if(!['pending','completed'].includes(r.status))throw new ProviderError('invalid_upload_state');if(r.status==='completed')return{id:uploadId,state:'completed',fileId:id(r.file?.id)};if(typeof r.upload_url!=='string'||(r.upload_method??'PUT')!=='PUT')throw new ProviderError('unsupported_upload_method');const headers=r.upload_headers??{};if(!headers||Array.isArray(headers)||Object.entries(headers).some(([k,v])=>typeof v!=='string'||/[\r\n]/.test(k+v)))throw new ProviderError('invalid_upload_headers');return{id:uploadId,state:'pending',url:r.upload_url,method:'PUT',headers};}
 async prepare(r:Request){if(r.pages||r.model)throw new ProviderError('unsupported_capability');return this.upload(await this.transport.json('uploads','POST',{filename:r.filename,bytes:r.size,mime_type:'application/pdf',purpose:'parse',sha256sum:r.sha256}));}
 async inspectUpload(uploadId:string){return this.upload(await this.transport.json(`uploads/${encodeURIComponent(id(uploadId))}`));}
 async transfer(u:Upload,bytes:Buffer){if(u.state==='completed')return;if(!u.url)throw new ProviderError('upload_url_missing');await this.transport.bytes(u.url,{method:u.method,headers:u.headers,body:bytes as unknown as BodyInit},1024*1024,Math.min(1800000,60000+Math.ceil(bytes.length/1048576)*2000));}
 async complete(uploadId:string){return this.upload(await this.transport.json(`uploads/${encodeURIComponent(id(uploadId))}/complete`,'POST'));}
 async submit(r:Request,fileId?:string){if(r.pages||r.model)throw new ProviderError('unsupported_capability');const source=fileId?{type:'file_id',file_id:id(fileId)}:{type:'url',url:r.url};const result=await this.transport.json('parse/jobs','POST',{files:[{source}],tier:r.tier,output_formats:r.formats});return id(result.job_id);}
 async status(jobId:string):Promise<Snapshot>{const r=await this.transport.json(`parse/jobs/${encodeURIComponent(id(jobId))}`);if(id(r.job_id)!==jobId)throw new ProviderError('identity_mismatch');const states:Record<string,Snapshot['state']>={queued:'pending',running:'running',completed:'succeeded',partial:'partial',failed:'failed',canceled:'cancelled',cancelled:'cancelled'};const outputs:Output[]=[],missing:string[]=[];if(!Array.isArray(r.files)||r.files.length!==1)throw new ProviderError('invalid_provider_response');for(const [index,f] of r.files.entries()){if(f.status!=='completed'){missing.push(`file-${index}:${states[f.status]??'unknown'}`);continue;}if(!f.output_files||typeof f.output_files!=='object')throw new ProviderError('invalid_provider_response');for(const [format,ref] of Object.entries(f.output_files)){const fileId=id((ref as any)?.file_id);outputs.push({id:fileId,fileId,format});}}return{id:jobId,state:states[r.status]??'unknown',outputs,missing};}
 async download(output:Output){if(!output.fileId)throw new ProviderError('output_identity_missing');return this.transport.apiBytes(`files/${encodeURIComponent(id(output.fileId))}/content`);}
}
